export const CONTRACT_ADDRESS = process.env.REACT_APP_CONTRACT_ADDRESS;
export const IDENTITY_REGISTRY_ADDRESS = process.env.REACT_APP_IDENTITY_REGISTRY_ADDRESS;
export const CREDENTIAL_VERIFIER_ADDRESS = process.env.REACT_APP_CREDENTIAL_VERIFIER_ADDRESS;

